name: "Moabi"
description: "Moabi is a collaborative mapping platform to monitor landuse planning in the Democratic Republic of the Congo."
baseurl: /site
permalink: /:title/:categories/
markdown: kramdown
prose:
  rooturl: "_posts/blog"
  siteurl: "http://crowdcover.github.io/site/"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog_post"
      - name: "tags"
        field:
          element: "hidden"
          value: "blog_post"
      - name: "language"
        field:
          element: "hidden"
          value: "en"
      - name: "categories"
        field:
          element: "hidden"
          value: "en"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "subtitle"
        field:
          element: "text"
          label: "Summary"
          help: "add a few lines of text for a short summary."
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "CrowdCover Team"
      - name: "img"
        field:
          element: "text"
          label: "Banner Photo"
          help: "URL link to a photo you would like to use for the banner photograph.  These can be hosted on flickr or elsewhere."
          value: ""
          placeholder: "http://example_photo_url.com"
# _posts/fr config should match _posts config,
# except for translated text values [currently both are in english]
# and categories and tags should match their respective language abbrev.
    _posts/fr:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog_post"
      - name: "tags"
        field:
          element: "hidden"
          value: "blog_post"
      - name: "language"
        field:
          element: "hidden"
          value: "fr"
      - name: "categories"
        field:
          element: "hidden"
          value: "fr"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Summary"
          help: "add a few lines of text for a short summary, to appear on the blog roll page: http://rdc.moabi.org/blog/fr/ .  If necessary, copy and paste one of your lead paragraphs"
          value: ""
          placeholder: "..."
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "CrowdCover Team"
          placeholder: "..."
      - name: "img"
        field:
          element: "text"
          label: "Banner Photo"
          help: "URL link to a photo you would like to use for the banner photograph.  These can be hosted on flickr or elsewhere."
          value: ""
          placeholder: "http://example_photo_url.com"

